// Auto-generated by LibreLane
module VRAI_SYNC_CORE(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input CLK,
  input RESET,
  input[31:0] INSTR_STREAM,
  output[15:0] INSTR_ADDR,
  output MAIN_STRH,
  output MAIN_STRW,
  output MAIN_LDH,
  output MAIN_LDW,
  output DEVICES_STRH,
  output DEVICES_STRW,
  output DEVICES_LDH,
  output DEVICES_LDW,
  output INVALID_MEM,
  output[15:0] MEM_STR_DATA,
  output[15:0] MEM_ADDR,
  input[15:0] MEM_LD_DATA,
  output EX_HALT
);
endmodule
