module CTZ_2
(
    input wire [1:0] A,

    output wire COUNT2,
    output wire COUNT1,
    output wire COUNT0
);

assign COUNT2 = ~A[1] & ~A[0]; //2 TRAILING ZEROS IF BOTH BITS ARE ZERO
assign COUNT1 = ~COUNT2 & ~A[0]; //1 TRAILING ZERO IF THE LEAST SIGNIFICANT BIT IS ZERO AND THE NEXT BIT IS ONE
assign COUNT0 = A[0]; //0 TRAILING ZEROS IF THE LEAST SIGNIFICANT BIT IS ONE

endmodule

module CTZ_4
(
    input wire [3:0] A,

    output wire COUNT4,
    output wire COUNT3,
    output wire COUNT2,
    output wire COUNT1,
    output wire COUNT0
);
wire HI_COUNT_2, HI_COUNT_1, HI_COUNT_0;
wire LO_COUNT_2, LO_COUNT_1, LO_COUNT_0;

CTZ_2 CTZ_HI (
    .A(A[3:2]),
    .COUNT2(HI_COUNT_2),
    .COUNT1(HI_COUNT_1),
    .COUNT0(HI_COUNT_0)
);

CTZ_2 CTZ_LO (
    .A(A[1:0]),
    .COUNT2(LO_COUNT_2),
    .COUNT1(LO_COUNT_1),
    .COUNT0(LO_COUNT_0)
);

assign COUNT0 = LO_COUNT_0;
assign COUNT1 = LO_COUNT_1;
assign COUNT2 = LO_COUNT_2 & HI_COUNT_0; //2 TRAILING ZEROS IF THE LO PART HAS 2 TRAILING ZEROS AND THE HI PART HAS 0 TRAILING ZEROS
assign COUNT3 = LO_COUNT_2 & HI_COUNT_1; //3 TRAILING ZEROS IF THE LO PART HAS 2 TRAILING ZEROS AND THE HI PART HAS 1 TRAILING ZERO
assign COUNT4 = LO_COUNT_2 & HI_COUNT_2; //4 TRAILING ZEROS IF THE LO PART HAS 2 TRAILING ZEROS AND THE HI PART HAS 2 TRAILING ZEROS

endmodule

module CTZ_8
(
    input wire [7:0] A,

    output wire COUNT8,
    output wire COUNT7,
    output wire COUNT6,
    output wire COUNT5,
    output wire COUNT4,
    output wire COUNT3,
    output wire COUNT2,
    output wire COUNT1,
    output wire COUNT0
);
wire HI_COUNT_4, HI_COUNT_3, HI_COUNT_2, HI_COUNT_1, HI_COUNT_0;
wire LO_COUNT_4, LO_COUNT_3, LO_COUNT_2, LO_COUNT_1, LO_COUNT_0;

CTZ_4 CTZ_HI (
    .A(A[7:4]),
    .COUNT4(HI_COUNT_4),
    .COUNT3(HI_COUNT_3),
    .COUNT2(HI_COUNT_2),
    .COUNT1(HI_COUNT_1),
    .COUNT0(HI_COUNT_0)
);

CTZ_4 CTZ_LO (
    .A(A[3:0]),
    .COUNT4(LO_COUNT_4),
    .COUNT3(LO_COUNT_3),
    .COUNT2(LO_COUNT_2),
    .COUNT1(LO_COUNT_1),
    .COUNT0(LO_COUNT_0)
);

assign COUNT0 = LO_COUNT_0;
assign COUNT1 = LO_COUNT_1;
assign COUNT2 = LO_COUNT_2;
assign COUNT3 = LO_COUNT_3;
assign COUNT4 = LO_COUNT_4 & HI_COUNT_0; //4 TRAILING ZEROS IF THE LO PART HAS 4 TRAILING ZEROS AND THE HI PART HAS 0 TRAILING ZEROS
assign COUNT5 = LO_COUNT_4 & HI_COUNT_1; //5 TRAILING ZEROS IF THE LO PART HAS 4 TRAILING ZEROS AND THE HI PART HAS 1 TRAILING ZERO
assign COUNT6 = LO_COUNT_4 & HI_COUNT_2; //6 TRAILING ZEROS IF THE LO PART HAS 4 TRAILING ZEROS AND THE HI PART HAS 2 TRAILING ZEROS
assign COUNT7 = LO_COUNT_4 & HI_COUNT_3; //7 TRAILING ZEROS IF THE LO PART HAS 4 TRAILING ZEROS AND THE HI PART HAS 3 TRAILING ZEROS
assign COUNT8 = LO_COUNT_4 & HI_COUNT_4; //8 TRAILING ZEROS IF THE LO PART HAS 4 TRAILING ZEROS AND THE HI PART HAS 4 TRAILING ZEROS

endmodule

module CTZ_16
(
    input wire [15:0] A,

    output wire [4:0] COUNT
);

wire HI_COUNT_8, HI_COUNT_7, HI_COUNT_6, HI_COUNT_5, HI_COUNT_4, HI_COUNT_3, HI_COUNT_2, HI_COUNT_1, HI_COUNT_0;
wire LO_COUNT_8, LO_COUNT_7, LO_COUNT_6, LO_COUNT_5, LO_COUNT_4, LO_COUNT_3, LO_COUNT_2, LO_COUNT_1, LO_COUNT_0;

CTZ_8 CTZ_HI (
    .A(A[15:8]),
    .COUNT8(HI_COUNT_8),
    .COUNT7(HI_COUNT_7),
    .COUNT6(HI_COUNT_6),
    .COUNT5(HI_COUNT_5),
    .COUNT4(HI_COUNT_4),
    .COUNT3(HI_COUNT_3),
    .COUNT2(HI_COUNT_2),
    .COUNT1(HI_COUNT_1),
    .COUNT0(HI_COUNT_0)
);

CTZ_8 CTZ_LO (
    .A(A[7:0]),
    .COUNT8(LO_COUNT_8),
    .COUNT7(LO_COUNT_7),
    .COUNT6(LO_COUNT_6),
    .COUNT5(LO_COUNT_5),
    .COUNT4(LO_COUNT_4),
    .COUNT3(LO_COUNT_3),
    .COUNT2(LO_COUNT_2),
    .COUNT1(LO_COUNT_1),
    .COUNT0(LO_COUNT_0)
);

wire COUNT_10;
wire COUNT_F;
wire COUNT_E;
wire COUNT_D;
wire COUNT_C;
wire COUNT_B;
wire COUNT_A;
wire COUNT_9;
//wire COUNT_8;
wire COUNT_7;
wire COUNT_6;
wire COUNT_5;
wire COUNT_4;
wire COUNT_3;
wire COUNT_2;
wire COUNT_1;
//wire COUNT_0;

//assign COUNT_0 = LO_COUNT_0;
assign COUNT_1 = LO_COUNT_1;
assign COUNT_2 = LO_COUNT_2;
assign COUNT_3 = LO_COUNT_3;
assign COUNT_4 = LO_COUNT_4;
assign COUNT_5 = LO_COUNT_5;
assign COUNT_6 = LO_COUNT_6;
assign COUNT_7 = LO_COUNT_7;
//assign COUNT_8 = LO_COUNT_8 & HI_COUNT_0; //8 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 0 TRAILING ZEROS
assign COUNT_9 = LO_COUNT_8 & HI_COUNT_1; //9 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 1 TRAILING ZERO
assign COUNT_A = LO_COUNT_8 & HI_COUNT_2; //10 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 2 TRAILING ZEROS
assign COUNT_B = LO_COUNT_8 & HI_COUNT_3; //11 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 3 TRAILING ZEROS
assign COUNT_C = LO_COUNT_8 & HI_COUNT_4; //12 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 4 TRAILING ZEROS
assign COUNT_D = LO_COUNT_8 & HI_COUNT_5; //13 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 5 TRAILING ZEROS
assign COUNT_E = LO_COUNT_8 & HI_COUNT_6; //14 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 6 TRAILING ZEROS 
assign COUNT_F = LO_COUNT_8 & HI_COUNT_7; //15 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 7 TRAILING ZEROS  
assign COUNT_10 = LO_COUNT_8 & HI_COUNT_8; //16 TRAILING ZEROS IF THE LO PART HAS 8 TRAILING ZEROS AND THE HI PART HAS 8 TRAILING ZEROS

assign COUNT[4] = COUNT_10;
assign COUNT[3] = LO_COUNT_8 & ~HI_COUNT_8;
assign COUNT[2] = COUNT_4 | COUNT_5 | COUNT_6 | COUNT_7 | COUNT_C | COUNT_D | COUNT_E | COUNT_F;
assign COUNT[1] = COUNT_2 | COUNT_3 | COUNT_6 | COUNT_7 | COUNT_A | COUNT_B | COUNT_E | COUNT_F;
assign COUNT[0] = COUNT_1 | COUNT_3 | COUNT_5 | COUNT_7 | COUNT_9 | COUNT_B | COUNT_D | COUNT_F;

endmodule