
create_clock -period 26 [get_ports CLK]

set_load 0.05 [all_outputs]

set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[31]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[30]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[29]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[28]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[27]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[26]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[25]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[24]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[23]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[22]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[21]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[20]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[19]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[18]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[17]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[16]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[15]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[14]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[13]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[12]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[11]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[10]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[9]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[8]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[7]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[6]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[5]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[4]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[3]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[2]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[1]]
set_input_delay -clock CLK 5.0 [get_ports INSTR_STREAM[0]]

set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[15]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[14]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[13]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[12]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[11]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[10]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[9]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[8]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[7]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[6]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[5]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[4]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[3]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[2]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[1]]
set_input_delay -clock CLK 5.0 [get_ports MEM_LD_DATA[0]]

set_input_delay -clock CLK 5.0 [get_ports RESET]